do not submit an empty registry
ropensci-org/makeregistry pull request #51
Opened 2021-01-28 10:15 UTC by maelle

2021-02-01 20:16 UTC, sckott commented
@maelle  should I have a look at this PR?

2021-02-03 05:08 UTC, maelle commented
Yes please

2021-02-03 19:37 UTC, sckott requested changes
tested the shell stuff locally - should work - just need to fix that variable mis-spelled

2021-02-03 19:37 UTC, sckott commented on inst/automation/make_registry.sh
> +    echo "Only $pkglength package(s), this is not good. :-("
`pkglength` !=  `pkgslength `

2021-02-05 13:45 UTC, maelle commented on inst/automation/make_registry.sh
> +    echo "Only $pkglength package(s), this is not good. :-("
thanks, now fixed.

2021-02-05 16:34 UTC, sckott approved these changes

2021-02-05 17:06 UTC, maelle commented
Can you merge or is it dangerous on a Friday? 🙂

2021-02-05 17:54 UTC, sckott commented
lets try it, i can roll it back if it doesn't work

2021-02-05 17:54 UTC, merged

2021-02-05 18:14 UTC, sckott commented
@maelle everything went smoothly i think 

https://github.com/ropensci-org/makeregistry/runs/1840791741?check_suite_focus=true
https://github.com/ropensci/roregistry/commit/805d8e4c370d7c1bf83d3e2427be575bb03a9512